s(n,[age = "Second", sex = "F", chest_pain_type = "NAP", restingBP = "Optimal", cholesterol = "Extremely high", fastingBS = 0, restingECG = "LVH", maxHR = 4, exercise_angina = "N", oldpeak = "Low risk", st_slope = "Up"]).
s(n,[age = "Third", sex = "F", chest_pain_type = "ASY", restingBP = "Normal/high", cholesterol = "Extremely high", fastingBS = 0, restingECG = "Normal", maxHR = 2, exercise_angina = "N", oldpeak = "High risk", st_slope = "Flat"]).
s(n,[age = "Second", sex = "F", chest_pain_type = "NAP", restingBP = "Normal/high", cholesterol = "Extremely high", fastingBS = 0, restingECG = "LVH", maxHR = 3, exercise_angina = "N", oldpeak = "Normal risk", st_slope = "Up"]).
s(n,[age = "Second", sex = "F", chest_pain_type = "ATA", restingBP = "Optimal", cholesterol = "Moderately high", fastingBS = 0, restingECG = "Normal", maxHR = 4, exercise_angina = "N", oldpeak = "Low risk", st_slope = "Up"]).
s(y,[age = "Second", sex = "M", chest_pain_type = "ASY", restingBP = "High", cholesterol = "Moderately high", fastingBS = 0, restingECG = "Normal", maxHR = 2, exercise_angina = "Y", oldpeak = "High risk", st_slope = "Down"]).
s(n,[age = "Second", sex = "M", chest_pain_type = "ATA", restingBP = "Normal/high", cholesterol = "Extremely high", fastingBS = 0, restingECG = "LVH", maxHR = 4, exercise_angina = "N", oldpeak = "Low risk", st_slope = "Up"]).
s(n,[age = "Second", sex = "M", chest_pain_type = "TA", restingBP = "Normal/high", cholesterol = "Desiderable", fastingBS = 0, restingECG = "LVH", maxHR = 4, exercise_angina = "N", oldpeak = "High risk", st_slope = "Flat"]).
s(y,[age = "Third", sex = "F", chest_pain_type = "ASY", restingBP = "Very high", cholesterol = "Moderately high", fastingBS = 1, restingECG = "Normal", maxHR = 4, exercise_angina = "Y", oldpeak = "Normal risk", st_slope = "Flat"]).
s(y,[age = "Second", sex = "M", chest_pain_type = "TA", restingBP = "Normal/high", cholesterol = "Moderately high", fastingBS = 0, restingECG = "Normal", maxHR = 4, exercise_angina = "Y", oldpeak = "High risk", st_slope = "Flat"]).
s(y,[age = "Third", sex = "F", chest_pain_type = "ASY", restingBP = "High", cholesterol = "Extremely high", fastingBS = 0, restingECG = "Normal", maxHR = 3, exercise_angina = "Y", oldpeak = "Normal risk", st_slope = "Flat"]).
s(n,[age = "Second", sex = "M", chest_pain_type = "ATA", restingBP = "Normal/high", cholesterol = "Extremely high", fastingBS = 0, restingECG = "Normal", maxHR = 3, exercise_angina = "N", oldpeak = "Low risk", st_slope = "Up"]).
s(y,[age = "Third", sex = "M", chest_pain_type = "NAP", restingBP = "High", cholesterol = "Extremely high", fastingBS = 0, restingECG = "LVH", maxHR = 3, exercise_angina = "N", oldpeak = "High risk", st_slope = "Flat"]).